# Generated by Django 4.2.6 on 2023-11-07 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('branch_code', models.CharField(help_text='4 uppercase letters or numbers', max_length=4, unique=True)),
                ('counter', models.PositiveIntegerField(default=1)),
                ('country_code', models.CharField(max_length=25)),
                ('timezone', models.CharField(max_length=50)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_name', models.CharField(max_length=25)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('select_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_desk', to='visitorsdesk.branches')),
            ],
        ),
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_phone', models.CharField(max_length=25)),
                ('user_name', models.CharField(max_length=25)),
                ('user_role', models.CharField(choices=[('Manager', 'Manager'), ('Staff', 'Staff'), ('Host', 'Host')], max_length=25)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('primary_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='visitorsdesk.branches')),
            ],
        ),
        migrations.CreateModel(
            name='NewVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=25)),
                ('purpose', models.CharField(max_length=25)),
                ('visitor_id', models.CharField(blank=True, max_length=6, null=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('checkin_time', models.DateTimeField(auto_now_add=True)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('select_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_new_visitor', to='visitorsdesk.branches')),
                ('select_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_new_visitor', to='visitorsdesk.desk')),
                ('user_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_new_visitor', to='visitorsdesk.mainuser')),
            ],
        ),
        migrations.CreateModel(
            name='InviteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('visitor_phone', models.CharField(max_length=25)),
                ('visitor_id', models.CharField(max_length=8)),
                ('purpose', models.CharField(max_length=25)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('select_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_vistor', to='visitorsdesk.branches')),
                ('user_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_user', to='visitorsdesk.mainuser')),
            ],
            options={
                'unique_together': {('visitor_id', 'select_branch')},
            },
        ),
        migrations.CreateModel(
            name='InvitedVisitorCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_id', models.CharField(max_length=25)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invited_visitor_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_visitor_branch', to='visitorsdesk.branches')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_visitor_checks', to='visitorsdesk.invitevisitor')),
            ],
        ),
        migrations.CreateModel(
            name='ExitVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_time', models.DateTimeField()),
                ('visitor_remarks', models.TextField()),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exit_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_desk', to='visitorsdesk.desk')),
            ],
        ),
    ]
