# Generated by Django 4.2.6 on 2023-11-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvisitor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
