# Generated by Django 4.2.6 on 2023-11-13 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitorsdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='branch_code',
            field=models.CharField(help_text='4 uppercase letters or numbers', max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='branches',
            unique_together={('auth_user', 'branch_code')},
        ),
    ]
