# Generated by Django 4.2.6 on 2023-12-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsdesk', '0002_alter_invitevisitor_visitors_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitevisitor',
            name='visitors_status',
            field=models.CharField(choices=[('Booked Visitor', 'Booked Visitor'), ('Invited Visitor', 'Invited Visitor')], max_length=25),
        ),
    ]
