# Generated by Django 4.2.6 on 2023-11-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsdesk', '0002_alter_newvisitor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitvisitor',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
