# Generated by Django 4.2.6 on 2023-12-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsdesk', '0002_alter_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitvisitor',
            name='exit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
