# Generated by Django 4.2.6 on 2023-11-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsdesk', '0002_alter_branches_branch_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='user_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
