# Generated by Django 4.2.6 on 2023-12-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsdesk', '0004_event_checked_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitevisitor',
            name='visitors_status',
        ),
    ]
