# Generated by Django 4.2.6 on 2023-12-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsdesk', '0006_alter_exitvisitor_exit_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='company',
            new_name='company_id',
        ),
    ]
