# Generated by Django 4.2.6 on 2023-12-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsdesk', '0009_rename_company_id_branch_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
