# Generated by Django 4.2.6 on 2023-12-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsdesk', '0010_mainuser_about_mainuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=25)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
            ],
        ),
    ]
