# Generated by Django 4.2.6 on 2023-12-19 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitorsdesk', '0012_remove_event_event_date_remove_event_event_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auth_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visitorsdesk.company'),
        ),
    ]
