# Generated by Django 4.2.6 on 2023-12-21 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsdesk', '0013_event_auth_user_event_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_host', to='visitorsdesk.mainuser'),
        ),
        migrations.AddField(
            model_name='event',
            name='visitor_email',
            field=models.EmailField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='visitor_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
