# Generated by Django 4.2.6 on 2023-12-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsdesk', '0014_event_staff_event_visitor_email_event_visitor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visitor_phone',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
